### ISSUE TITLE
add bg for loginpage

### ISSUE THREAD

**Issue by daviise** [daviise/upturnlogin#4]
https://github.com/daviise/upturnlogin/blob/master/css/img/5.jpg
https://github.com/daviise/upturnlogin/blob/master/css/img/8.jpg

**Comment by ndmtuan** [comment]
i can do it. please assign me

**Comment by daviise** [comment]
Thanks for taking this up!!!! @ndmtuan

**Comment by ndmtuan** [comment]
@daviise  thanks you so much!!!!

**Comment by ndmtuan** [comment]
![image](https://user-images.githubusercontent.com/90179780/141711061-f29a1680-c2ea-4665-b4f6-4a036659e312.png)

This is my result, please review it @daviise . I added the background form to make it easier to see

**Comment by daviise** [comment]
This is awesome 🎉. Can you create PR?  I will start reviewing. @ndmtuan

**Comment by ndmtuan** [comment]
oke!! Thank you so much!! @daviise

**Comment by vonet999** [comment]
i can do it . Can you assign me
